"""2024-05-02T18:21:51.120341

Revision ID: 19c8456c1cca
Revises: c316cbd1ece6
Create Date: 2024-05-02 18:21:52.540302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19c8456c1cca"
down_revision = "c316cbd1ece6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_public_subject_name"),
        "subject",
        ["name"],
        unique=True,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_university_short_name"),
        "university",
        ["short_name"],
        unique=True,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_university_short_name"),
        table_name="university",
        schema="public",
    )
    op.drop_index(op.f("ix_public_subject_name"), table_name="subject", schema="public")
    # ### end Alembic commands ###
