"""2024-05-02T18:34:21.435884

Revision ID: 43d933e1a516
Revises: 19c8456c1cca
Create Date: 2024-05-02 18:34:21.666491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43d933e1a516"
down_revision = "19c8456c1cca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "summary",
        "university",
        ["university_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "summary",
        "subject",
        ["subject_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "summary",
        "teacher",
        ["teacher_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "summary", schema="public", type_="foreignkey")
    op.drop_constraint(None, "summary", schema="public", type_="foreignkey")
    op.drop_constraint(None, "summary", schema="public", type_="foreignkey")
    # ### end Alembic commands ###
