"""2024-05-16T15:14:30.592999

Revision ID: 66a6d573bcea
Revises: bb7620a921b4
Create Date: 2024-05-16 15:14:30.900303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a6d573bcea'
down_revision = 'bb7620a921b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'date_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('date_birth', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
