"""2024-05-05T16:45:40.830525

Revision ID: bb7620a921b4
Revises: db79be051828
Create Date: 2024-05-05 16:45:41.104445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bb7620a921b4"
down_revision = "db79be051828"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("teacher_university_id_fkey", "teacher", type_="foreignkey")
    op.drop_column("teacher", "subject_ids")
    op.drop_column("teacher", "university_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teacher",
        sa.Column("university_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "teacher",
        sa.Column(
            "subject_ids",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "teacher_university_id_fkey", "teacher", "university", ["university_id"], ["id"]
    )
    # ### end Alembic commands ###
