"""2024-02-27T00:32:02.369178

Revision ID: c316cbd1ece6
Revises: 4785abde7d85
Create Date: 2024-02-27 00:32:02.680869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c316cbd1ece6"
down_revision = "4785abde7d85"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("lecture_summary_id_fkey", "lecture", type_="foreignkey")
    op.create_foreign_key(
        None,
        "lecture",
        "summary",
        ["summary_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint("teacher_university_id_fkey", "teacher", type_="foreignkey")
    op.create_foreign_key(
        None,
        "teacher",
        "university",
        ["university_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teacher", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "teacher_university_id_fkey", "teacher", "university", ["university_id"], ["id"]
    )
    op.drop_constraint(None, "lecture", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "lecture_summary_id_fkey", "lecture", "summary", ["summary_id"], ["id"]
    )
    # ### end Alembic commands ###
