"""2024-06-30T16:55:50.369156

Revision ID: d1ee60161dcc
Revises: 66a6d573bcea
Create Date: 2024-06-30 16:55:50.621739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1ee60161dcc"
down_revision = "66a6d573bcea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("summary_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_moderated", sa.Boolean(), nullable=False),
        sa.Column("is_complain", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment", schema="public")
    # ### end Alembic commands ###
